version:
yamlCreatedInVersion: ${project.version}
apiLink: 'https://api.github.com/repos/TreeboMC/CreativeCancel/releases/latest'
releasePage: 'https://github.com/TreeboMC/CreativeCancel/releases/latestt'
checkUpdates: 'true'

maxEnchantLevel: 10

BlockedItems:
  Example_World:
    TRIDENT: TRIDENT

ConsoleNotify: true

messages:
  badge: '[CreativeCancel] - '
  showBlocked: 'The following items have are currently blocked on this world.'
  itemBlocked: 'You have blocked XXXITEMXXX on this world.'
  itemUnblocked: 'You have unblocked XXXITEMXXX  on this world.'
  noCommandPerm: 'Im sorry XXXPLAYERXXX, but you lack sufficient privileges to use Creative Cancel.'
  animate: 'Im sorry XXXPLAYERXXX, but we have elected to disallow the use of XXXITEMXXX on this world'
  changedHotbar: 'Im sorry XXXPLAYERXXX, but we have elected to disallow the use of XXXITEMXXX on this world'
  itemDropped: 'Im sorry XXXPLAYERXXX, but we have elected to disallow the use of XXXITEMXXX on this world'
  closeInventory: 'Im sorry XXXPLAYERXXX, but we have elected to disallow the use of XXXITEMXXX on this world'